---
name: "Build and Publish Images on Release"

on:
  release:
    types:
      - published

jobs:
  generator:
    strategy:
      fail-fast: true
      matrix:
        version:
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"

    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Login to Github Container Registry
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build Image
        env:
          PHP_VERSION: ${{ matrix.version }}
          RELEASE: ${{ github.ref_name }}
        run: |
          IMAGE_BASENAME=$(echo "ghcr.io/${{ secrets.GHCR_ACTOR }}/php-boilerplate" | tr '[A-Z]' '[a-z]')
          docker build . \
            --file php_fpm-${PHP_VERSION}/Dockerfile \
            --label "org.opencontainers.image.source=https://github.com/${{ secrets.GHCR_ACTOR }}/docker-php7.3-fpm" \
            --label "org.opencontainers.image.url=https://github.com/${{ secrets.GHCR_ACTOR }}/docker-php7.3-fpm" \
            --label "org.opencontainers.image.created=$(date -Iseconds)" \
            --label "org.opencontainers.image.version=${RELEASE}" \
            --tag base-swoole:php-${PHP_VERSION} \
            --tag ${IMAGE_BASENAME}:php-${PHP_VERSION} \
            --tag ${IMAGE_BASENAME}:${RELEASE}_php-${PHP_VERSION}

      - name: Build Swoole Image
        env:
          PHP_VERSION: ${{ matrix.version }}
          RELEASE: ${{ github.ref_name }}
        run: |
          if [ -f "php_fpm-${PHP_VERSION}/Dockerfile.swoole" ]; then
            IMAGE_BASENAME=$(echo "ghcr.io/${{ secrets.GHCR_ACTOR }}/php-boilerplate" | tr '[A-Z]' '[a-z]')
            docker build . \
              --file php_fpm-${PHP_VERSION}/Dockerfile.swoole \
              --label "org.opencontainers.image.source=https://github.com/${{ secrets.GHCR_ACTOR }}/docker-php7.3-fpm" \
              --label "org.opencontainers.image.url=https://github.com/${{ secrets.GHCR_ACTOR }}/docker-php7.3-fpm" \
              --label "org.opencontainers.image.created=$(date -Iseconds)" \
              --label "org.opencontainers.image.version=swoole-${RELEASE}" \
              --tag ${IMAGE_BASENAME}:swoole-${PHP_VERSION} \
              --tag ${IMAGE_BASENAME}:${RELEASE}_swoole-${PHP_VERSION}
          else
            echo "Swoole requires PHP version > 8.0.0."
          fi

      - name: Push new Image to Github Container Registry
        env:
          PHP_VERSION: ${{ matrix.version }}
          RELEASE: ${{ github.ref_name }}
        run: |
          IMAGE_BASENAME=$(echo "ghcr.io/${{ secrets.GHCR_ACTOR }}/php-boilerplate" | tr '[A-Z]' '[a-z]')
          docker push ${IMAGE_BASENAME}:php-${PHP_VERSION}
          docker push ${IMAGE_BASENAME}:${RELEASE}_php-${PHP_VERSION}
          if [ -f "php_fpm-${PHP_VERSION}/Dockerfile.swoole" ]; then
            docker push ${IMAGE_BASENAME}:swoole-${PHP_VERSION}
            docker push ${IMAGE_BASENAME}:${RELEASE}_swoole-${PHP_VERSION}
          fi
